"""Import the jcreate palette / font libraries into JIZURA (jAlpha edition).

usage: python tools/import_library.py [--palettes PATH] [--fonts PATH]
  -> src/11r_library.js  (generated; do not edit by hand — rerun this after the libraries change)

Palettes: every entry of palettes.js (id, name, category, hex colours).
Fonts:    Google Fonts entries of fonts.js (system fonts are skipped: they cannot be loaded on other PCs).
          Families JIZURA already has are skipped at runtime by src/11s_library.js.
"""
import argparse, json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ap = argparse.ArgumentParser()
ap.add_argument('--palettes', default='E:/jcreate_app/palettes/palettes.js')
ap.add_argument('--fonts', default='E:/jcreate_app/fonts/fonts.js')
ap.add_argument('--out', default=os.path.join(ROOT, 'src', '11r_library.js'))
a = ap.parse_args()


def read_array(path, name):
    # the library files are JS (with comments); let Node evaluate them and hand back JSON
    js = ("const fs=require('fs');const src=fs.readFileSync(process.argv[1],'utf8');"
          "process.stdout.write(JSON.stringify(new Function(src+';return '+process.argv[2])()));")
    r = subprocess.run(['node', '-e', js, path, name], capture_output=True)
    if r.returncode:
        sys.exit(f'{path}: {name} を読めませんでした\n' + r.stderr.decode('utf-8', 'replace'))
    return json.loads(r.stdout.decode('utf-8'))


HEX = re.compile(r'^#[0-9A-Fa-f]{6}$')
palettes = []
for p in read_array(a.palettes, 'PALETTES'):
    cols = [c['hex'].upper() for c in p.get('colors', []) if HEX.match(c.get('hex', ''))]
    if len(cols) < 3:
        print('skip palette (fewer than 3 colours):', p.get('id'))
        continue
    palettes.append({'id': p['id'], 'name': p.get('name', p['id']), 'category': p.get('category', ''), 'colors': cols})

KIND = {'ゴシック': 'gothic', '明朝': 'mincho', '丸ゴシック': 'round', '手書き・筆': 'hand', 'デザイン': 'display',
        'Sans': 'latin', 'Serif': 'latin', 'Display': 'latin', 'Mono': 'mono'}
fonts = []
for f in read_array(a.fonts, 'FONTS'):
    if f.get('source') != 'google' or not f.get('google'):
        continue
    weights = sorted(int(w) for w in (f.get('weights') or [400]))
    w = weights[-1]
    fonts.append({'id': f['id'], 'family': f['google'], 'label': f.get('name', f['google']), 'weight': w,
                  'kind': KIND.get(f.get('category', ''), 'gothic'), 'jp': f.get('script') == 'jp',
                  'gf': f['google'].replace(' ', '+') + (f':wght@{w}' if len(weights) > 1 or w != 400 else '')})

body = ('/* GENERATED by tools/import_library.py from the jcreate palette / font libraries — do not edit by hand. */\n'
        '(() => {\n\'use strict\';\n'
        'J.LIB_PALETTES = ' + json.dumps(palettes, ensure_ascii=False, separators=(',', ':')) + ';\n'
        'J.LIB_FONT_DEFS = ' + json.dumps(fonts, ensure_ascii=False, separators=(',', ':')) + ';\n'
        '})();\n')
open(a.out, 'w', encoding='utf-8', newline='\n').write(body)
print(f'{os.path.relpath(a.out, ROOT)}: {len(palettes)} palettes, {len(fonts)} Google fonts')
