/* ============================================================
   JIZURA (jAlpha edition) — jcreate palette / font libraries
   Data comes from src/11r_library.js (generated by tools/import_library.py).
   - Palettes (P01…) replace a style's colour schemes: project.colors.palette = { id, v, cols }
     (v = which palette colour becomes the main background; cols = copy of the colours, used when the
     id is no longer in the library). The user's accent / background overrides still apply on top.
   - Fonts (F01…) are added to J.FONTS as lib_f01 … (families + weights JIZURA already has are skipped).
   - Random picks use library palettes / Japanese library fonts only when project.lib === true.
   ============================================================ */
(() => {
'use strict';
const JP_SANS_FB = '"Noto Sans JP","Noto Sans CJK JP","Hiragino Sans","Yu Gothic","Meiryo",sans-serif';
const JP_SERIF_FB = '"Noto Serif JP","Noto Serif CJK JP","Hiragino Mincho ProN","Yu Mincho",serif';
const SERIF = { mincho: 1, hand: 1 };

/* ---------- fonts ---------- */
J.LIB_FONTS = [];
const have = new Set(Object.values(J.FONTS).map(f => f.family.replace(/"/g, '') + '|' + f.weight));
for (const d of J.LIB_FONT_DEFS || []) {
  if (have.has(d.family + '|' + d.weight)) continue;
  const key = 'lib_' + d.id.toLowerCase();
  J.FONTS[key] = {
    label: `${d.id} ${d.label}${d.weight !== 400 ? ' ' + d.weight : ''}`, family: `"${d.family}"`, weight: d.weight,
    kind: d.kind, fb: SERIF[d.kind] ? JP_SERIF_FB : JP_SANS_FB, gf: d.gf, extra: true, lib: true, jp: d.jp,
  };
  J.LIB_FONTS.push(key);
}

/* ---------- palettes ---------- */
J.LIB_PALETTE_BY_ID = Object.fromEntries((J.LIB_PALETTES || []).map(p => [p.id, p]));
const sat = h => { const [, s, l] = J.toHsl(h); return s * (1 - Math.abs(2 * l - 1)); };   // chroma-like: vivid mid tones first
const readable = (bg) => J.contrast('#FFFFFF', bg) >= J.contrast('#000000', bg) ? '#FFFFFF' : '#000000';   // one of them always reaches 4.58
/* the palette colours ordered as main-background candidates: darkest, lightest, 2nd darkest, 2nd lightest … */
J.paletteBgOrder = cols => {
  const s = [...cols].sort((a, b) => J.lum(a) - J.lum(b)), out = [];
  for (let i = 0, j = s.length - 1; i <= j; i++, j--) { out.push(s[i]); if (j !== i) out.push(s[j]); }
  return out;
};
function schemeFor(bg, cols, base) {
  const others = cols.filter(c => c !== bg);
  const byContrast = [...others].sort((a, b) => J.contrast(b, bg) - J.contrast(a, bg));
  let fg = byContrast[0] ? J.fitContrast(byContrast[0], bg, 4.5) : readable(bg);
  if (J.contrast(fg, bg) < 4.5) fg = readable(bg);
  const rest = others.filter(c => c !== byContrast[0]).sort((a, b) => sat(b) - sat(a));
  const a1 = rest[0] || byContrast[0] || fg, a2 = rest[1] || rest[0] || fg;
  const accent = J.fitContrast(a1, bg, 2.4), accent2 = J.fitContrast(a2, bg, 1.6);
  const o = Object.assign({}, base, {
    bg: bg.toUpperCase(), fg, sub: J.mix(fg, bg, 0.3).toUpperCase(), accent, accent2, ink: fg,
    dim: J.mix(bg, fg, 0.1).toUpperCase(), ghostA: J.fitContrast(a1, bg, 1.35), ghostB: J.fitContrast(a2 === a1 ? fg : a2, bg, 1.35),
  });
  if (base && base.grad) o.grad = [accent, J.mix(accent, bg, 0.5)];
  return o;
}
/* project.colors.palette → colour schemes (as many as the style has, 2–3) */
J.paletteSchemes = (pal, baseSchemes) => {
  const lib = J.LIB_PALETTE_BY_ID[pal.id];
  const cols = (lib ? lib.colors : pal.cols || []).filter(c => /^#[0-9a-f]{6}$/i.test(c));
  if (cols.length < 2) return baseSchemes;
  const order = J.paletteBgOrder(cols);
  const bg0 = pal.bg && cols.includes(pal.bg) ? pal.bg : order[((pal.v | 0) % order.length + order.length) % order.length];   // brand kits name their background
  // second background: the palette colour furthest from the first; third: the most vivid one left
  const bg1 = [...cols].filter(c => c !== bg0).sort((a, b) => J.contrast(b, bg0) - J.contrast(a, bg0))[0];
  const bgs = [bg0, bg1];
  if (baseSchemes.length > 2) { const r = cols.filter(c => !bgs.includes(c)).sort((a, b) => sat(b) - sat(a))[0]; if (r) bgs.push(r); }
  return bgs.map((bg, i) => schemeFor(bg, cols, baseSchemes[i % baseSchemes.length]));
};
J.libPaletteValue = (id, v = 0) => { const p = J.LIB_PALETTE_BY_ID[id]; return p ? { id, v, cols: p.colors.slice() } : null; };
J.randomLibPalette = (rnd = Math.random) => {
  const L = J.LIB_PALETTES || []; if (!L.length) return null;
  const p = L[Math.floor(rnd() * L.length) % L.length];
  return J.libPaletteValue(p.id, Math.floor(rnd() * 2));   // mostly the darkest or lightest colour as the main background
};

/* ---------- random picks ---------- */
// library fonts: random only with the library switch on, and only faces with Japanese glyphs
const baseRandomOk = J.randomOk;
J.randomOk = (project, g, k) => {
  if (g === 'font' && J.FONTS[k] && J.FONTS[k].lib) return !!(project && project.lib === true) && !!J.FONTS[k].jp && J.FONTS[k].kind !== 'mono';
  return baseRandomOk(project, g, k);
};
})();
